# Add this line to resolve react_native_pods.rb with Node.js
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BasicApp' do
  config = use_native_modules!

  # Explicitly set the Node.js binary path
  ENV['NODE_BINARY'] = '/Users/sulemanbaloch/.nvm/versions/node/v18.20.5/bin/node'

  # Enable Hermes explicitly
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false # Ensure Hermes is disabled if not needed
  )
  
  # Explicitly disable new architecture
  ENV['RCT_NEW_ARCH_ENABLED'] = '0'
  

  target 'BasicAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Post-install configuration
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true # Uncomment if ccache is configured
    )
  end
end
